### ISSUE TITLE
Final copy of dwi file to proper output folder errors with 'file not found'

### ISSUE THREAD

**Issue by bacaron** [brainlife/app-qsiprep#4]
Hello,

I was testing this app with a dataset I've been working on and I noticed that although the app errored out on brainlife, it looked like everything successfully ran. When I looked into the .err file, I noticed this final error:

> cp: cannot stat ‘output/qsiprep/sub-*/dwi/sub-*_space-T1w_desc-preproc_dwi.nii.gz’: No such file or directory

When I looked at the directory tree, I noticed the existence of a 'ses-1' directory immediately following the 'sub-*' directory (see attached image of directory tree).

![Screenshot from 2022-03-04 10-35-45](https://user-images.githubusercontent.com/22106265/156793838-d41d8c47-6716-4dc0-8cef-8dc75ab6f9eb.png)

I'm guessing this is related to the archived data in the project on brainlife having session identifiers, which is not super common at this point. I imagine this is a simple fix (hopefully).

I can happily work on this and submit a PR if that helps!

Thanks,
Brad C

**Comment by soichih** [comment]
I had a similar issue while working with fmriprep output. I had to do hacky things like these..

> https://github.com/brainlife/app-fmriprep/blob/master/fmriprep2bl.sh#L17
> https://github.com/brainlife/app-fmriprep/blob/master/fmriprep2bl.sh#L71

Maybe we could interface with pybids and let it do the enumeration instead of doing it like this in bash script?

**Comment by bacaron** [comment]
Oh cool I wasn't aware of pybids.

I tested it on the output dataset, but it doesn't seem to actually work. It looks like the output file isn't fully bids formatted somehow. Not sure what's up or what's the best approach to go from here, but if we could get pybids to work that would be awesome!

**Comment by soichih** [comment]
Darn it!

**Comment by bacaron** [comment]
my reaction as well haha

**Comment by giulia-berto** [comment]
Hi @bacaron, I just transferred what @soichih did for fmriprep, hopefully it works!

**Comment by bacaron** [comment]
thank you @giulia-berto! Testing now. Will close if works.

**Comment by giulia-berto** [comment]
Fixed.
